apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scp-keyvault-01
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: <identity-id>
    keyvaultName: <kv-name>
    objects:  |
      array:
        - |
          objectName: configurable-secrets
          objectType: secret
          objectAlias: secret.json
    tenantId: <tenant-id>