apiVersion: apps/v1
kind: Deployment
metadata:
  name: rngapi
  labels: 
    kubernetes.courselabs.co: containerprobes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rngapi
  template:
    metadata:
      labels:
        app: rngapi
    spec:
      containers:
        - name: app
          image: kiamol/ch03-numbers-api
          env:
            - name: FailAfterCallCount
              value: "1"
